# .readthedocs.yaml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - echo "Pre build"
      - echo "Cleaning..."
      - rm -rf $READTHEDOCS_OUTPUT/html docs/doxygen/* docs/source/api/* docs/source/readme/*
      - echo "Doxygen..."
      - doxygen Doxyfile
      - echo "Api generation..."
      - python3 scripts/auto_doc/api_rst_generator.py

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt    
