from .efem import unitary_test
from .efem import defineEFEMConstants
from .efem import nedelecBasisIterative
from .efem import computeEdges
from .efem import computeFaces
from .efem import computeBoundaryFaces
from .efem import computeBoundaryEdges
from .efem import computeBoundaries
from .efem import computeElementDOFs
from .efem import edgeFaceVerticesInit
from .efem import computeSignsJacobLegth
from .efem import definitionHighOrderTet
from .efem import computeCoefficientsSecondOrder
from .efem import nedelecBasisSecondOrder
from .efem import computeMassMatrixSecondOrder
from .efem import computeStiffnessMatrixSecondOrder
from .efem import computeCoefficientsThirdOrder
from .efem import nedelecBasisThirdOrder
from .efem import computeMassMatrixThirdOrder
from .efem import computeStiffnessMatrixThirdOrder
from .fem import tetraXiEtaZeta2XYZ
from .fem import gauss_points_tetrahedron
from .fem import gauss_points_reference_tetrahedron
from .fem import volumetricToCartesianCoordinates
from .fem import cartesianToVolumetricCoordinates
from .vectorMatrixFunctions import deleteDuplicateRows
from .vectorMatrixFunctions import findUniqueRows
from .vectorMatrixFunctions import crossprod
from .vectorMatrixFunctions import is_duplicate_entry
