from .efem import unitary_test
from .efem import defineEFEMConstants
from .efem import nedelecBasisIterative
from .efem import computeDofs
from .efem import computeFaces
from .efem import computeBoundaryFaces
from .efem import computeBoundaryDofs
from .fem import tetraXiEtaZeta2XYZ
from .fem import gauss_points_tetrahedron
from .vectorMatrixFunctions import deleteDuplicateRows
from .vectorMatrixFunctions import findUniqueRows
