#!/usr/bin/env bash

# ============================================================================
# CSEM inversion benchmark (im2): synthetic observations
#
# This script adds Gaussian noise to the forward responses and writes the
# synthetic observations that the inversion tries to fit:
#
#   true model -> forward modelling -> [ observations + noise ] ->
#   inversion -> recovered model
#
# It calls the general utility utils/make_observed.py with fixed parameters,
# so the noise realisation is reproducible. The seed is set below, stored in
# the output file and quoted in reference/reference_metrics.json. Changing
# SEED or ERROR_LEVEL invalidates the reference metrics.
#
# The seed differs from the one used in examples/im1, so the two cases have
# independent noise realisations.
#
# Usage (from the repository root):
#   bash examples/im2/scripts/make_observations.sh
#
#   With the petgem-env image:
#   docker run --rm -u $(id -u):$(id -g) -v "$PWD":/workspace -w /workspace \
#       petgem-env:latest bash examples/im2/scripts/make_observations.sh
#
# Required input:
#   outputs/responses_fm_f<F>_p2.h5
#     Generated by scripts/run_fm.slurm
#
# Generated output:
#   outputs/observed.h5
#
# Next step:
#   bash examples/im2/scripts/build_bundles.sh im
#
# Notes:
#   - Requires the petgem Python package.
# ============================================================================

set -euo pipefail

CASE_DIR=examples/im2
FREQS=1,10,50,100,300,800,1500
SEED=20260922
ERROR_LEVEL=0.01

# Check that every forward response is available.
missing=0
for F in ${FREQS//,/ }; do
  if [[ ! -f "${CASE_DIR}/outputs/responses_fm_f${F}_p2.h5" ]]; then
    echo "ERROR: missing ${CASE_DIR}/outputs/responses_fm_f${F}_p2.h5"
    missing=1
  fi
done
if [[ "${missing}" -ne 0 ]]; then
  echo "Run the forward stage first:"
  echo "  build_bundles.sh fm -> run_fm.slurm"
  exit 1
fi

echo "============================================================"
echo "Generating synthetic observations"
echo "============================================================"
echo "Case directory : ${CASE_DIR}"
echo "Frequencies    : ${FREQS}"
echo "Seed           : ${SEED}"
echo "Noise level    : ${ERROR_LEVEL}"
echo

python3 utils/make_observed.py \
    -case_dir    "${CASE_DIR}" \
    -pattern     "outputs/responses_fm_f{freq}_p2.h5" \
    -freqs       "${FREQS}" \
    -seed        "${SEED}" \
    -error_level "${ERROR_LEVEL}" \
    -out         outputs/observed.h5

echo
echo "Observations ready: ${CASE_DIR}/outputs/observed.h5"
