# ###############################################################################
# # PETGEM parameters file
# ###############################################################################
# Model parameters
model:
  mode: csem    # Modeling mode: csem or mt
  csem:
    sigma:
      #file: 'my_file.h5'                # Conductivity model file
      horizontal: [1., 0.01, 1., 3.3333]  # Horizontal conductivity
      vertical: [1., 0.01, 1., 3.3333]    # Vertical conductivity
    source:
      frequency: 2.                     # Frequency (Hz)
      position: [1750., 1750., -975.]   # Source position (xyz)
      azimuth: 0.                       # Source rotation in xy plane (in degrees)
      dip: 0.                           # Source rotation in xz plane (in degrees)
      current: 1.                       # Source current (Am)
      length: 1.                        # Source length  (m)

  # Common parameters for all models
  mesh: examples/case1/DIPOLE1D.msh   # Mesh file (gmsh format v2)
  receivers: examples/case1/receiver_pos.h5 # Receiver positions file (xyz)

# Execution parameters
run:
  nord: 1       # Vector basis order (1,2,3,4,5,6)
  cuda: False   # Cuda support (True or False)

# Output parameters
output:
  vtk: True                               # Postprocess vtk file (EM fields, conductivity)
  directory: examples/case1/out           # Directory for output (results)
  directory_scratch: examples/case1/tmp   # Directory for temporal files
