# =============================================================================== #
# RELEASE DOCKERFILE FOR PETGEM (runtime only)                                     #
# =============================================================================== #
FROM ubuntu:22.04 AS runtime

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# ---------------------------
# Copy PETGEM runtime binaries from develop build stage
# ---------------------------
COPY --from=builder /usr/local/petsc /usr/local/petsc
COPY --from=builder /usr/local/gmsh /usr/local/gmsh
COPY --from=builder /usr/local/extrae /usr/local/extrae
COPY --from=builder /usr/lib/python3 /usr/lib/python3
COPY --from=builder /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY --from=builder /usr/local/bin /usr/local/bin

# ---------------------------
# Environment variables
# ---------------------------
ENV PETSC_DIR=/usr/local/petsc
ENV PETSC_ARCH=arch-linux-c-opt
ENV GMSH_DIR=/usr/local/gmsh/bin
ENV EXTRAE_DIR=/usr/local/extrae
ENV PATH="$PETSC_DIR/$PETSC_ARCH/bin:$GMSH_DIR:$EXTRAE_DIR/bin:$PATH"

# Default command
CMD ["bash"]
