# =============================================================================== #
# STAGE 1: Builder (all dependencies + compilation + Python packages)             #
# =============================================================================== #
FROM ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# ---------------------------
# Install build & runtime dependencies
# ---------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc gfortran g++ make cmake vim \
    flex bison libtool git wget autoconf automake autopoint pkg-config gettext libtool-bin \
    python3 python3-pip python3-distutils \
    libglu1 libxcursor1 tzdata libxinerama1 \
    texinfo doxygen latexmk \
    texlive-latex-base texlive-latex-extra texlive-fonts-recommended \
    python3-breathe python3-meshio python3-h5py python3-numpy python3-matplotlib \
    python3-sphinx python3-sphinx-rtd-theme \
    && pip3 install --no-cache-dir cython \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# ---------------------------
# PETSc
# ---------------------------
ENV PETSC_DIR=/usr/local/petsc
ENV PETSC_ARCH=arch-linux-c-opt
WORKDIR /usr/local/petsc
RUN git clone -b release https://gitlab.com/petsc/petsc.git . \
    && git pull \
    && ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran \
       --download-mpich --download-fblaslapack \
       --with-scalar-type=complex --download-mumps --download-scalapack --download-ptscotch \
       --download-cmake --with-debugging=1 --download-hdf5 --download-triangle \
    && make $PETSC_DIR $PETSC_ARCH all \
    && make check \
    && pip3 install src/binding/petsc4py

# ---------------------------
# GMSH
# ---------------------------
ENV GMSH_DIR=/usr/local/gmsh
RUN mkdir -p $GMSH_DIR
WORKDIR /workspace
RUN wget http://gmsh.info/bin/Linux/gmsh-stable-Linux64.tgz \
    && tar -xf gmsh-stable-Linux64.tgz -C $GMSH_DIR --strip-components=1

# ---------------------------
# Extrae dependencies
# ---------------------------
ENV EXTRAE_DIR=/usr/local/extrae
RUN mkdir -p $EXTRAE_DIR/libunwind $EXTRAE_DIR/papi $EXTRAE_DIR/libxml2 $EXTRAE_DIR/binutils

# libunwind
WORKDIR /workspace
RUN git clone https://github.com/libunwind/libunwind.git \
    && cd libunwind \
    && autoreconf -i \
    && ./configure --prefix=$EXTRAE_DIR/libunwind \
    && make && make install

# PAPI
WORKDIR /workspace
RUN git clone https://github.com/icl-utk-edu/papi \
    && cd papi/src \
    && ./configure --prefix=$EXTRAE_DIR/papi CC=gcc F77=gfortran \
    && make && make install

# binutils
WORKDIR /workspace
RUN wget http://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.gz \
    && tar -xf binutils-2.42.tar.gz \
    && cd binutils-2.42 \
    && ./configure --prefix=$EXTRAE_DIR/binutils --enable-shared CFLAGS="-g -O2 -Wno-error" CXXFLAGS="-g -O2 -Wno-error" \
    && make && make install && cp libiberty/pic/libiberty.a $EXTRAE_DIR/binutils/lib

# libxml2
WORKDIR /workspace
RUN git clone --branch v2.13.0 https://gitlab.gnome.org/GNOME/libxml2.git \
    && cd libxml2 \
    && ./autogen.sh --prefix=$EXTRAE_DIR/libxml2 --without-python \
    && make && make install

# Extrae
WORKDIR /workspace
RUN git clone https://github.com/bsc-performance-tools/extrae.git \
    && cd extrae \
    && git submodule update --init --recursive \
    && autoreconf -f -i \
    && ./configure --prefix=$EXTRAE_DIR \
        --with-mpi=$PETSC_DIR/$PETSC_ARCH/ \
        --with-papi=$EXTRAE_DIR/papi \
        --with-xml-prefix=$EXTRAE_DIR/libxml2 \
        --with-unwind=$EXTRAE_DIR/libunwind \
        --with-binutils=$EXTRAE_DIR/binutils \
        --without-dyninst --disable-openmp \
    && make -j1 && make install

# Cleanup unnecessary files
RUN rm -rf /workspace/*

# =============================================================================== #
# STAGE 2: Runtime image                                                        #
# =============================================================================== #
FROM ubuntu:22.04 AS runtime

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# Copy all built binaries and Python packages from builder
COPY --from=builder /usr/local/petsc /usr/local/petsc
COPY --from=builder /usr/local/gmsh /usr/local/gmsh
COPY --from=builder /usr/local/extrae /usr/local/extrae
COPY --from=builder /usr/lib/python3 /usr/lib/python3
COPY --from=builder /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY --from=builder /usr/local/bin /usr/local/bin

# Environment variables
ENV PETSC_DIR=/usr/local/petsc
ENV PETSC_ARCH=arch-linux-c-opt
ENV GMSH_DIR=/usr/local/gmsh/bin
ENV EXTRAE_DIR=/usr/local/extrae
ENV PATH="$PETSC_DIR/$PETSC_ARCH/bin:$GMSH_DIR:$EXTRAE_DIR/bin:$PATH"

CMD ["bash"]
