#!/usr/bin/env bash

# ============================================================================
# CSEM inversion benchmark (im1): input bundles
#
# This script calls the general preprocessor utils/preprocess.py with the
# mesh, survey and conductivity files of this benchmark and writes the HDF5
# bundles read by the PETGEM solvers. It has two stages:
#   fm  Seven forward bundles on the true model (geometry/mesh_true.msh),
#       one per frequency
#   im  One inverse bundle with the starting model (geometry/mesh.msh) and
#       the observed data
#
# Usage (from the repository root):
#   bash examples/im1/scripts/build_bundles.sh <fm|im>
#
#   With the petgem-env image:
#   docker run --rm -u $(id -u):$(id -g) -v "$PWD":/workspace -w /workspace \
#       petgem-env:latest bash examples/im1/scripts/build_bundles.sh <fm|im>
#
# Required input:
#   fm  survey/ and geometry/ files of the true model
#   im  outputs/observed.h5
#         Generated by scripts/make_observations.sh
#
# Generated output:
#   fm  outputs/input_fm_f<F>.h5
#   im  outputs/input_im.h5
#
# Notes:
#   - Requires the petgem Python package and meshio.
#   - No observed dataset is shipped. The benchmark is meant to be run end to
#     end, so the inversion always uses the observations of the current run.
#   - Set OBSERVED=<path>, relative to the case directory, to use another
#     observations file.
# ============================================================================

set -euo pipefail

STAGE="${1:?stage: fm|im}"
CASE_DIR=examples/im1
ORDER=2
FREQS="1 10 50 100 300 800 1500"
OBSERVED="${OBSERVED:-outputs/observed.h5}"

mkdir -p "${CASE_DIR}/outputs"

echo "============================================================"
echo "Building the im1 input bundles (stage: ${STAGE})"
echo "============================================================"
echo "Case directory : ${CASE_DIR}"
echo "Order          : ${ORDER}"
echo

case "${STAGE}" in
  fm)
    # One forward bundle per frequency on the true model.
    for F in ${FREQS}; do
      python3 utils/preprocess.py -mode fm -order "${ORDER}" -case_dir "${CASE_DIR}" \
          -mesh_filename     geometry/mesh_true.msh \
          -receiver_filename survey/receivers.txt \
          -source_filename   "survey/sources_f${F}.txt" \
          -sigma_file        survey/sigmas_true.txt \
          -input_filename    "outputs/input_fm_f${F}.h5" \
          -params_filename   "outputs/_pp_fm_f${F}.txt"
    done
    echo
    echo "Forward bundles ready: ${CASE_DIR}/outputs/input_fm_f*.h5"
    ;;
  im)
    # The inversion needs the observations generated earlier in the pipeline.
    if [[ ! -f "${CASE_DIR}/${OBSERVED}" ]]; then
      echo "ERROR: missing ${CASE_DIR}/${OBSERVED}"
      echo "Run the pipeline in order:"
      echo "  build_bundles.sh fm -> run_fm.slurm -> make_observations.sh"
      exit 1
    fi
    python3 utils/preprocess.py -mode im -order "${ORDER}" -case_dir "${CASE_DIR}" \
        -mesh_filename      geometry/mesh.msh \
        -receiver_filename  survey/receivers.txt \
        -im_source_filename survey/sources_im.txt \
        -observed_filename  "${OBSERVED}" \
        -error_level        0.01 \
        -sigma_file         survey/sigmas_im.txt \
        -input_filename     outputs/input_im.h5 \
        -params_filename    outputs/_pp_im.txt
    echo
    echo "Inverse bundle ready: ${CASE_DIR}/outputs/input_im.h5"
    ;;
  *)
    echo "ERROR: stage must be fm or im"
    exit 1
    ;;
esac
