#!/bin/bash

# ============================================================================
# PETSc build for PETGEM on MareNostrum 5
#
# This script configures, builds and installs PETSc with the options PETGEM
# needs (complex scalars, 64-bit indices, MUMPS, ParMETIS, HDF5). It then
# writes petgem_env.sh, the file that scripts/mn5/set_env.sh loads.
#
# Usage:
#   bash compile_petsc.sh                        # PETSc 3.26.0, all steps
#   PETSC_VERSION=3.27.0 bash compile_petsc.sh   # another PETSc version
#   bash compile_petsc.sh env                    # only rewrite petgem_env.sh
#
# Steps:
#   configure | build | install | env | all (default)
#
# Required input:
#   PETSc source tree in ${PETSC_BASE}/petsc-v<version>
#
# Generated output:
#   <prefix>/petgem_env.sh
#   ${PETSC_BASE}/petsc-current -> <prefix>
#
# Notes:
#   - Run this script on a login node.
#   - Every path, module list and compiler below can be overridden through
#     an environment variable of the same name.
# ============================================================================

set -euo pipefail

PETSC_BASE="${PETSC_BASE:-/gpfs/scratch/bsc115/$USER}"
PETSC_VERSION="${PETSC_VERSION:-3.26.0}"
SRC="${SRC:-$PETSC_BASE/petsc-v$PETSC_VERSION}"
PREFIX="${PREFIX:-$SRC/install}"
ARCH="${ARCH:-linux-x86_64-opt}"
RUN_MODULES="${RUN_MODULES:-oneapi hdf5}"
BUILD_MODULES="${BUILD_MODULES:-cmake}"
MPICC="${MPICC:-mpiicc}"
MPICXX="${MPICXX:-mpiicpc}"
MPIFC="${MPIFC:-mpiifort}"
NP="${NP:-8}"
STEP="${1:-all}"

[ -x "$SRC/configure" ] || { echo "ERROR: no PETSc source in $SRC"; exit 1; }

# Load the modules needed at run time and at build time.
module purge
module load $RUN_MODULES
# Pin run modules to their loaded versions.
PINNED=$(for m in $RUN_MODULES; do
  tr ':' '\n' <<<"${LOADEDMODULES:-}" | grep -m1 "^${m%%/*}/" || echo "$m"
done | xargs)
module load $BUILD_MODULES
: "${MKLROOT:?MKLROOT not set after 'module load $RUN_MODULES'}"
echo "PETSc $PETSC_VERSION  src=$SRC  prefix=$PREFIX  arch=$ARCH"
echo "run modules: $PINNED"

do_configure() {
  cd "$SRC"
  ./configure \
    --PETSC_DIR="$SRC" \
    --with-petsc-arch="$ARCH" \
    --prefix="$PREFIX" \
    --with-scalar-type=complex \
    --with-debugging=0 \
    --with-64-bit-indices=1 \
    --with-cc="$MPICC" \
    --with-cxx="$MPICXX" \
    --with-fc="$MPIFC" \
    --with-shared-libraries=1 \
    --with-mpi=1 \
    --with-fortran-bindings=0 \
    --download-mumps \
    --with-scalapack \
    --download-parmetis \
    --download-metis \
    --with-blaslapack-dir="$MKLROOT" \
    --with-hdf5 \
    --download-triangle
}

do_build() {
  make -C "$SRC" PETSC_DIR="$SRC" PETSC_ARCH="$ARCH" MAKE_NP="$NP" all
}

do_install() {
  make -C "$SRC" -f makefile --eval=.PHONY:install PETSC_DIR="$SRC" PETSC_ARCH="$ARCH" install
}

do_env() {
  [ -f "$PREFIX/lib/petsc/conf/variables" ] \
    || { echo "ERROR: no PETSc install in $PREFIX"; exit 1; }
  # BDDC primal-dof fix (PETSc MR 9628).
  if [ "$(grep -c 'PCBDDCAddPrimalVerticesLocalIS(pc, primals)' \
          "$SRC/src/ksp/pc/impls/bddc/bddcprivate.c" 2>/dev/null)" != 2 ]; then
    echo "WARNING: $SRC lacks the BDDC primal-dof fix (MR 9628)"
  fi
  cat > "$PREFIX/petgem_env.sh" <<EOF
# Generated by compile_petsc.sh on $(date -Iseconds).
# PETSc $PETSC_VERSION ($(git -C "$SRC" describe --always 2>/dev/null || echo no-git)), arch $ARCH
module purge
module load $PINNED
export PETSC_DIR=$PREFIX
unset PETSC_ARCH
EOF
  ln -sfn "$PREFIX" "$PETSC_BASE/petsc-current"
  echo "wrote $PREFIX/petgem_env.sh; $PETSC_BASE/petsc-current -> $PREFIX"
}

case "$STEP" in
  configure) do_configure ;;
  build)     do_build ;;
  install)   do_install ;;
  env)       do_env ;;
  all)       do_configure; do_build; do_install; do_env ;;
  *) echo "usage: $0 [configure|build|install|env|all]"; exit 1 ;;
esac
