# sync_rtd_docs.py
import re
import os
from pathlib import Path

# --- SCRIPT GLOBAL CONFIGURATION ---
README_FILE_PATH = "README.rst"  # Path to the main README file
DOCS_BASE_DIR = "docs"          # Base directory where .rst files are generated
# Ensure INDEX_FILE_PATH uses the correct path, assuming it's inside DOCS_BASE_DIR/source
# If your index.rst is in docs/source/index.rst, this is the configuration:
INDEX_FILE_PATH = os.path.join(DOCS_BASE_DIR, "source", "index.rst") # Main toctree file

# Markers for the autogenerated toctree section
TOC_START_MARKER = ".. AUTOGENERATED-TOC-START"
TOC_END_MARKER = ".. AUTOGENERATED-TOC-END"
# --- END OF CONFIGURATION ---

# Regular expression to parse the rtd-sync-config directive
# Captures the directive block and its :key: value options
DIRECTIVE_RE = re.compile(
    r"^\.\.\s*\n"  # Initial ".." line followed by a newline
    r"\s+rtd-sync-config::\s*\n"  # Indented "rtd-sync-config::" line
    r"((?:\s+:[a-zA-Z0-9_-]+:.*?\n)+)"  # Block of options, also indented
    , re.MULTILINE
)
OPTION_RE = re.compile(r"^\s+:([a-zA-Z0-9_-]+):\s*(.*?)\s*$", re.MULTILINE)

# Regular expression to find RST section headers
SECTION_HEADER_RE = re.compile(
    r"^(?P<title_text>.+)\n"
    r"(?P<underline_char>[=\-`:'\"~^_*#.+])(?P=underline_char){2,}\n",
    re.MULTILINE
)

def parse_readme_for_sync_blocks(readme_content):
    """
    Parses the README.rst content to find rtd-sync-config blocks
    and their associated RST sections.
    Returns a list of dictionaries, each representing a block to process.
    """
    sync_blocks = []

    for directive_match in DIRECTIVE_RE.finditer(readme_content):
        options_text = directive_match.group(1)
        
        config = {}
        for opt_match in OPTION_RE.finditer(options_text):
            key = opt_match.group(1).strip()
            value = opt_match.group(2).strip()
            if key == "skip": # :skip: is an implicit boolean
                config[key] = True
            else:
                config[key] = value
        
        header_search_start_pos = directive_match.end()
        section_header_match = SECTION_HEADER_RE.search(readme_content, pos=header_search_start_pos)
        
        if not section_header_match:
            print(f"  [WARN] Directive at position {directive_match.start()} is not followed by a valid section header. Skipping.")
            continue

        # Check if another directive exists between the current directive and its section header
        next_directive_search_region = readme_content[directive_match.end():section_header_match.start()]
        if DIRECTIVE_RE.search(next_directive_search_region):
            print(f"  [WARN] Directive at position {directive_match.start()} appears to have another directive before its section. Skipping this instance.")
            continue

        section_title = section_header_match.group('title_text').strip()
        section_content_start_pos = section_header_match.end()

        # Determine the end of the current section's body
        next_element_search_pos = section_content_start_pos
        next_section_header_match = SECTION_HEADER_RE.search(readme_content, pos=next_element_search_pos)
        next_directive_match = DIRECTIVE_RE.search(readme_content, pos=next_element_search_pos)

        content_ends_at = len(readme_content)

        if next_section_header_match and next_directive_match:
            content_ends_at = min(next_section_header_match.start(), next_directive_match.start())
        elif next_section_header_match:
            content_ends_at = next_section_header_match.start()
        elif next_directive_match:
            content_ends_at = next_directive_match.start()
            
        section_body = readme_content[section_content_start_pos:content_ends_at].strip()

        sync_blocks.append({
            "config": config,
            "readme_title": section_title,
            "readme_content_body": section_body,
        })

    return sync_blocks


def generate_or_update_rst_file(block_info):
    """
    Generates or updates an .rst file based on the block information.
    Returns the relative path of the generated file (from project root)
    or None if not generated/updated.
    """
    config = block_info["config"]

    if config.get("skip", False):
        print(f"  -> Section '{block_info['readme_title']}' marked with :skip:. Skipping file generation.")
        return None

    target_path_from_config = config.get("target")
    if not target_path_from_config:
        print(f"  [ERROR] Section '{block_info['readme_title']}' has no :target: and is not :skip:ped. Cannot generate file.")
        return None

    # Path in :target: is expected to be relative to the project root
    target_abs_path = Path(target_path_from_config).resolve()

    target_abs_path.parent.mkdir(parents=True, exist_ok=True)

    title_in_doc = config.get("title_in_doc", block_info["readme_title"])
    content_body = block_info["readme_content_body"]

    underline_char = "="
    title_line = title_in_doc
    underline_line = underline_char * len(title_line)
    file_content = f"{title_line}\n{underline_line}\n\n{content_body}\n"

    try:
        existing_content = ""
        if target_abs_path.exists():
            with open(target_abs_path, 'r', encoding='utf-8') as f_read:
                existing_content = f_read.read()
        
        if existing_content.strip() == file_content.strip():
            print(f"  -> Content for '{target_abs_path}' has not changed. No write needed.")
        else:
            with open(target_abs_path, 'w', encoding='utf-8') as f_write:
                f_write.write(file_content)
            print(f"  -> File '{target_abs_path}' generated/updated for section '{block_info['readme_title']}'.")
        # Return the original config path, as this will be used for the toctree
        return target_path_from_config
    except IOError as e:
        print(f"  [ERROR] Writing to '{target_abs_path}': {e}")
        return None

def extract_toctree_config(sync_blocks):
    """
    Extracts toctree configuration from synchronization blocks.
    Returns a list of tuples (toctree_text, target_path_from_config).
    """
    toctree_entries = []
    for block in sync_blocks:
        toctree_entry_value = block["config"].get("toctree_entry")
        
        final_toctree_text = None
        if toctree_entry_value is None: # If :toctree_entry: is not present, use :title_in_doc: or README title
            final_toctree_text = block["config"].get("title_in_doc", block["readme_title"])
        elif toctree_entry_value != "": # If :toctree_entry: is present and not empty, use its value
            final_toctree_text = toctree_entry_value
        # If toctree_entry_value is "" (empty string), final_toctree_text remains None, so no entry is added
        
        if final_toctree_text: 
            target_path_from_config = generate_or_update_rst_file(block)
            if target_path_from_config: # Only add if file was actually generated/updated
                toctree_entries.append((final_toctree_text, target_path_from_config))
    return toctree_entries

def update_toctree(index_file_path_str, toc_entries_data):
    """
    Updates the toctree section in the index file.
    toc_entries_data is a list of (toctree_text, target_file_path_from_config).
    target_file_path_from_config is the path as specified in :target: (e.g., "docs/source/readme/file.rst").
    """
    index_file_path_obj = Path(index_file_path_str).resolve()
    if not index_file_path_obj.exists():
        print(f"[ERROR] Index file '{index_file_path_obj}' not found. Cannot update toctree.")
        return

    try:
        with open(index_file_path_obj, 'r', encoding='utf-8') as f:
            original_index_content = f.read()
    except IOError as e:
        print(f"[ERROR] Reading index file '{index_file_path_obj}': {e}")
        return

    toc_start_idx = original_index_content.find(TOC_START_MARKER)
    toc_end_idx = original_index_content.find(TOC_END_MARKER)

    if toc_start_idx == -1 or toc_end_idx == -1 or toc_end_idx <= toc_start_idx:
        print(f"[ERROR] Markers '{TOC_START_MARKER}' and/or '{TOC_END_MARKER}' not found or misplaced in '{index_file_path_obj}'.")
        print("        Ensure both markers exist and are in the correct order.")
        return

    prefix = original_index_content[:toc_start_idx + len(TOC_START_MARKER)]
    suffix = original_index_content[toc_end_idx:] 

    # Extract existing toctree options like :maxdepth: and :caption:
    existing_toctree_block = original_index_content[toc_start_idx:toc_end_idx]
    maxdepth_match = re.search(r":maxdepth:\s*(\d+)", existing_toctree_block)
    caption_match = re.search(r":caption:\s*(.+?)\n", existing_toctree_block) # Non-greedy match for caption
    
    maxdepth_option = f"   :maxdepth: {maxdepth_match.group(1) if maxdepth_match else 2}"
    caption_option = f"   :caption: {caption_match.group(1).strip() if caption_match else 'Autogenerated Content'}"

    new_toctree_lines = [".. toctree::", maxdepth_option, caption_option, ""]
    
    index_dir = index_file_path_obj.parent

    for _, target_path_str_from_config in toc_entries_data:
        if target_path_str_from_config:
            # Convert target path (relative to project root) to be relative to index.rst's directory
            target_abs_path = Path(target_path_str_from_config).resolve()
            try:
                path_relative_to_index_dir = os.path.relpath(target_abs_path, index_dir)
            except ValueError: # If on different drives (Windows)
                print(f"  [WARN] Could not calculate relative path for '{target_abs_path}' from '{index_dir}'. Using original path.")
                path_relative_to_index_dir = target_path_str_from_config # Fallback

            entry_path = Path(path_relative_to_index_dir).with_suffix('') # Remove .rst
            new_toctree_lines.append(f"   {entry_path.as_posix()}") # Use POSIX paths for Sphinx

    new_toctree_block = "\n".join(new_toctree_lines)
    updated_index_content = f"{prefix}\n\n{new_toctree_block}\n\n{suffix}"
    
    if original_index_content.strip() == updated_index_content.strip():
        print(f"  -> Toctree in '{index_file_path_obj}' has not changed. No write needed.")
    else:
        try:
            with open(index_file_path_obj, 'w', encoding='utf-8') as f:
                f.write(updated_index_content)
            print(f"  -> Toctree in '{index_file_path_obj}' updated.")
        except IOError as e:
            print(f"[ERROR] Writing updated index file '{index_file_path_obj}': {e}")


def main():
    readme_path_obj = Path(README_FILE_PATH).resolve()
    if not readme_path_obj.exists():
        print(f"[ERROR] README file '{readme_path_obj}' not found.")
        return

    print(f"Reading '{readme_path_obj}'...")
    try:
        with open(readme_path_obj, 'r', encoding='utf-8') as f:
            readme_content = f.read()
    except IOError as e:
        print(f"[ERROR] Reading '{readme_path_obj}': {e}")
        return

    print("Parsing README for 'rtd-sync-config' directives...")
    sync_blocks = parse_readme_for_sync_blocks(readme_content)

    if not sync_blocks:
        print("  -> No 'rtd-sync-config' blocks found to process in README.")
    else:
        print(f"  -> Found {len(sync_blocks)} sync blocks in README.")

    # extract_toctree_config will process sync_blocks (which may be empty).
    # If sync_blocks is empty, toc_entries_data will also be an empty list.
    # This function also calls generate_or_update_rst_file.
    toc_entries_data = extract_toctree_config(sync_blocks)

    # Always attempt to update the toctree.
    # If toc_entries_data is empty, update_toctree will generate an empty toctree block
    # (clearing previous entries but keeping options like :maxdepth: and :caption:).
    print(f"\nUpdating toctree in '{INDEX_FILE_PATH}'...")
    update_toctree(INDEX_FILE_PATH, toc_entries_data)

    # Informational message based on the outcome
    if not toc_entries_data:
        if not sync_blocks: # No blocks in README at all
            print(f"  -> No directives found in README. The toctree section in '{INDEX_FILE_PATH}' will have been cleared of entries (if it had any) or maintained if already empty.")
        else: # Blocks were in README, but didn't produce toctree entries
            print(f"  -> Although directives were found in README, none resulted in a valid toctree entry (e.g., due to :skip: or :toctree_entry: \"\"). The toctree section will have been cleared or maintained.")
    else:
        print(f"  -> Processed {len(toc_entries_data)} entries for the toctree.")

    print("\n--- Synchronization complete ---")

if __name__ == "__main__":
    main()